# Generated by Django 4.1.7 on 2023-03-30 02:31

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('number_of_bedrooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_beds', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_baths', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_adult_guests', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_child_guests', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('available', models.BooleanField()),
                ('available_from', models.DateTimeField()),
                ('available_to', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancellation_policy', models.CharField(choices=[('Free Cancellation', 'Free Cancellation'), ('Paid Cancellation', 'Paid Cancellation')], default='Free Cancellation', max_length=25)),
                ('cancellation_fee_per_night', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
