# Generated by Django 4.1.7 on 2023-03-31 15:30

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reservation.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Category',
                'verbose_name_plural': 'Property Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Property Feature Category',
                'verbose_name_plural': 'Property Feature Categories',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('size', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('number_of_bedrooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_beds', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_baths', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_adult_guests', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_child_guests', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('available', models.BooleanField()),
                ('available_from', models.DateTimeField()),
                ('available_to', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancellation_policy', models.CharField(choices=[('Free Cancellation', 'Free Cancellation'), ('Paid Cancellation', 'Paid Cancellation')], default='Free Cancellation', max_length=25)),
                ('cancellation_fee_per_night', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='reservation.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('rate', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reservation.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Review',
                'verbose_name_plural': 'Property Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='property/photos', validators=[reservation.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('video', models.FileField(blank=True, upload_to='property/videos', validators=[reservation.validators.validate_video_size, django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mkv', 'flv', 'wmv'])])),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='reservation.property')),
            ],
            options={
                'verbose_name': 'Property Media',
                'verbose_name_plural': 'Property Media',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('feature_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_features', to='reservation.featurecategory')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='reservation.property')),
            ],
            options={
                'verbose_name': 'Property Feature',
                'verbose_name_plural': 'Property Features',
            },
        ),
    ]
