# Generated by Django 4.2 on 2023-04-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='deposit',
        ),
        migrations.AddField(
            model_name='property',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
