# Generated by Django 4.2 on 2023-04-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_property_deposit_property_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='ip_address',
        ),
    ]
