# Generated by Django 4.2 on 2023-04-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_reservation_reservation_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_fees',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_in_nights',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_fees',
        ),
    ]
